# Python 

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

In [ ]:
def quicksort(eip):
    if len(eip) <= 1:
        return eip
    mlbr = eip[len(eip) // 2]
    eip_in = [x for x in eip if x < mlbr]
    eip_out = [x for x in eip if x == mlbr]
    mlblr_in = [x for x in eip if x > mlbr]
    return quicksort(eip_in) + eip_out + quicksort(mlblr_in)

print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"

Basic data types

Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.
Numbers: Integers and floats work as you would expect from other languages:

In [ ]:
eip = 3
print(type(eip)) # Prints "<class 'int'>"
print(eip)       # Prints "3"
print(eip + 1)   # Addition; prints "4"
print(eip - 1)   # Subtraction; prints "2"
print(eip * 2)   # Multiplication; prints "6"
print(eip ** 2)  # Exponentiation; prints "9"
eip += 1
print(eip)  # Prints "4"
eip *= 2
print(eip)  # Prints "8"
mlblr = 2.5
print(type(mlblr)) # Prints "<class 'float'>"
print(mlblr, mlblr + 1, mlblr * 2, mlblr ** 2) # Prints "2.5 3.5 5.0 6.25"

Booleans: 
Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [ ]:
eip = True
mlblr = False
print(type(eip)) # Prints "<class 'bool'>"
print(eip and mlblr) # Logical AND; prints "False"
print(eip or mlblr)  # Logical OR; prints "True"
print(not eip)   # Logical NOT; prints "False"
print(eip != mlblr)  # Logical XOR; prints "True"

Strings:
Python has great support for strings:

In [ ]:
eip = 'eip'    # String literals can use single quotes
mlblr = "mlblr"    # or double quotes; it does not matter.
print(eip)       # Prints "eip"
print(len(eip))  # String length; prints "5"
eip_in = eip + ' ' + mlblr  # String concatenation
print(eip_in)  # prints "eip mlblr"
eip_out = '%s %s %d' % (eip, mlblr, 12)  # sprintf style string formatting
print(hw12)  # prints "eip mlblr 12"

In [ ]:
eip = "hello"
print(eip.capitalize())  # Capitalize a string; prints "Hello"
print(eip.upper())       # Convert a string to uppercase; prints "HELLO"
print(eip.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(eip.center(7))     # Center a string, padding with spaces; prints " hello "
print(eip.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Containers:
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

In [ ]:
eip = [3, 1, 2]    # Create a list
print(eip, eip[2])  # Prints "[3, 1, 2] 2"
print(eip[-1])     # Negative indices count from the end of the list; prints "2"
eip[2] = 'foo'     # Lists can contain elements of different types
print(eip)         # Prints "[3, 1, 'foo']"
eip.append('bar')  # Add a new element to the end of the list
print(eip)         # Prints "[3, 1, 'foo', 'bar']"
x = eip.pop()      # Remove and return the last element of the list
print(x, eip)      # Prints "bar [3, 1, 'foo']"

Slicing: 
In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
mlblr = list(range(5))     # range is a built-in function that creates a list of integers
print(mlblr)               # Prints "[0, 1, 2, 3, 4]"
print(mlblr[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(mlblr[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(mlblr[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(mlblr[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(mlblr[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
mlblr[2:4] = [8, 9]        # Assign a new sublist to a slice
print(mlblr)               # Prints "[0, 1, 8, 9, 4]"

Loops: You can loop over the elements of a list like this:

In [ ]:
mlblrs = ['cat', 'dog', 'monkey']
for mlblr in mlblrs:
    print(mlblr)
# Prints "cat", "dog", "monkey", each on its own line.

In [ ]:
mlblrs = ['cat', 'dog', 'monkey']
for idx, mlblr in enumerate(mlblrs):
    print('#%d: %s' % (idx + 1, mlblr))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

List comprehensions: When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
eip = [0, 1, 2, 3, 4]
mlblr = []
for x in eip:
    mlblr.append(x ** 2)
print(mlblr)   # Prints [0, 1, 4, 9, 16]

In [ ]:
eip_in = [0, 1, 2, 3, 4]
mlblr_out = [x ** 2 for x in eip_in]
print(mlblr_out)   # Prints [0, 1, 4, 9, 16]

In [ ]:
eip = [0, 1, 2, 3, 4]
mlblr = [x ** 2 for x in eip if x % 2 == 0]
print(mlblr)  # Prints "[0, 4, 16]"

Dictionaries

A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:

In [ ]:
eip_dict = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(eip_dict['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in eip_dict)     # Check if a dictionary has a given key; prints "True"
eip_dict['fish'] = 'wet'     # Set an entry in a dictionary
print(eip_dict['fish'])      # Prints "wet"
# print(eip_dict['monkey'])  # KeyError: 'monkey' not a key of eip_dict
print(eip_dict.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(eip_dict.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del eip_dict['fish']         # Remove an element from a dictionary
print(eip_dict.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

Loops: It is easy to iterate over the keys in a dictionary:

In [ ]:
eip_dict = {'person': 2, 'cat': 4, 'spider': 8}
for animal in eip_dict:
    legs = eip_dict[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
eip_dict = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in eip_dict.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
eip_in = [0, 1, 2, 3, 4]
eip_out = {x: x ** 2 for x in eip_in if x % 2 == 0}
print(eip_out)  # Prints "{0: 0, 2: 4, 4: 16}"

Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
mlblr = {'cat', 'dog'}
print('cat' in mlblr)   # Check if an element is in a set; prints "True"
print('fish' in mlblr)  # prints "False"
mlblr.add('fish')       # Add an element to a set
print('fish' in mlblr)  # Prints "True"
print(len(mlblr))       # Number of elements in a set; prints "3"
mlblr.add('cat')        # Adding an element that is already in the set does nothing
print(len(mlblr))       # Prints "3"
mlblr.remove('cat')     # Remove an element from a set
print(len(mlblr))       # Prints "2"

In [ ]:
mlblrs = {'cat', 'dog', 'fish'}
for idx, mlblr in enumerate(mlblrs):
    print('#%d: %s' % (idx + 1, mlblr))
# Prints "#1: fish", "#2: dog", "#3: cat"

In [ ]:
from math import sqrt
eip_in = {int(sqrt(x)) for x in range(30)}
print(eip_in)  # Prints "{0, 1, 2, 3, 4, 5}"

Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
eip_dict = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
eip_tuple = (5, 6)        # Create a tuple
print(type(eip_tuple))    # Prints "<class 'tuple'>"
print(eip_dict[eip_tuple])       # Prints "5"
print(eip_dict[(1, 2)])  # Prints "1"

Functions

Python functions are defined using the def keyword. For example:

In [ ]:
def eip(d):
    if d > 0:
        return 'positive'
    elif d < 0:
        return 'negative'
    else:
        return 'zero'

for d in [-1, 0, 1]:
    print(eip(d))
# Prints "negative", "zero", "positive"

In [ ]:
def hello(eip, mlblr=False):
    if mlblr:
        print('HELLO, %s!' % eip.upper())
    else:
        print('Hello, %s' % eip)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', mlblr=True)  # Prints "HELLO, FRED!"

Classes

The syntax for defining classes in Python is straightforward:

In [ ]:
class EIP(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def eip(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = EIP('Fred')  # Construct an instance of the Greeter class
g.eip()            # Call an instance method; prints "Hello, Fred"
g.eip(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
import numpy as np

eip = np.array([1, 2, 3])   # Create a rank 1 array
print(type(eip))            # Prints "<class 'numpy.ndarray'>"
print(eip.shape)            # Prints "(3,)"
print(eip[0], eip[1], a[2])   # Prints "1 2 3"
eip[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

mlblr = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(mlblr.shape)                     # Prints "(2, 3)"
print(mlblr[0, 0], mlblr[0, 1], mlblr[1, 0])   # Prints "1 2 4"

In [ ]:
import numpy as np

eip = np.zeros((2,2))   # Create an array of all zeros
print(eip)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

mlblr = np.ones((1,2))    # Create an array of all ones
print(mlblr)              # Prints "[[ 1.  1.]]"

eip_in = np.full((2,2), 7)  # Create a constant array
print(eip_in)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
eip = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
eip_out = eip[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
eip_out[0, 0] = 77     # eip_out[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
eip = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = eip[1, :]    # Rank 1 view of the second row of eip
row_r2 = eip[1:2, :]  # Rank 2 view of the second row of eip
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = eip[:, 1]
col_r2 = eip[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
import numpy as np

eip = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(eip[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([eip[0, 0], eip[1, 1], eip[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(eip[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([eip[0, 1], eip[0, 1]]))  # Prints "[2 2]"

In [ ]:
import numpy as np

# Create a new array from which we will select elements
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(eip)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
mlblr = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(eip[np.arange(4), mlblr])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
eip[np.arange(4), mlblr] += 10

print(eip)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

In [ ]:
import numpy as np

eip = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (eip > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(eip[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(eip[eip > 2])     # Prints "[3 4 5 6]"

Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
import numpy as np

eip = np.array([1, 2])   # Let numpy choose the datatype
print(eip.dtype)         # Prints "int64"

eip = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(eip.dtype)             # Prints "float64"

eip = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(eip.dtype)                         # Prints "int64"

Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

eip = np.array([[1,2],[3,4]], dtype=np.float64)
mlblr = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(eip + mlblr)
print(np.add(eip, mlblr))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(eip - mlblr)
print(np.subtract(eip, mlblr))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(eip * mlblr)
print(np.multiply(eip, mlblr))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(eip / mlblr)
print(np.divide(eip, mlblr))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(eip))

In [ ]:
import numpy as np

eip = np.array([[1,2],[3,4]])
mlblr = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(eip.dot(v))
print(np.dot(eip, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(eip.dot(mlblr))
print(np.dot(eip, mlblr))

In [ ]:
import numpy as np

eip = np.array([[1,2],[3,4]])

print(np.sum(eip))  # Compute sum of all elements; prints "10"
print(np.sum(eip, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(eip, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
import numpy as np

eip = np.array([[1,2], [3,4]])
print(eip)    # Prints "[[1 2]
            #          [3 4]]"
print(eip.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
mlblr = np.array([1,2,3])
print(mlblr)    # Prints "[1 2 3]"
print(mlblr.T)  # Prints "[1 2 3]"

Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
mlblr = np.array([1, 0, 1])
eip_in = np.empty_like(eip)   # Create an empty matrix with the same shape as eip

# Add the vector mlblr to each row of the matrix eip with an explicit loop
for i in range(4):
    eip_in[i, :] = eip[i, :] + mlblr

# Now eip_in is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(eip_in)

In [ ]:
import numpy as np

# We will add the vector mlblr to each row of the matrix eip,
# storing the result in the matrix y
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
mlblr = np.array([1, 0, 1])
mlblr_in = np.tile(mlblr, (4, 1))   # Stack 4 copies of mlblr on top of each other
print(mlblr_in)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
eip_in = eip + mlblr_in  # Add eip and mlblr_in elementwise
print(eip_in)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [ ]:
import numpy as np

# We will add the vector eip_in to each row of the matrix eip,
# storing the result in the matrix mlblr
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip_in = np.array([1, 0, 1])
mlblr = eip + eip_in  # Add eip_in to each row of eip using broadcasting
print(mlblr)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [ ]:
import numpy as np

# Compute outer product of vectors
eip = np.array([1,2,3])  # eip has shape (3,)
eip_in = np.array([4,5])    # eip_in has shape (2,)
# To compute an outer product, we first reshape eip to be a column
# vector of shape (3, 1); we can then broadcast it against eip_in to yield
# an output of shape (3, 2), which is the outer product of eip and eip_in:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(eip, (3, 1)) * eip_in)

# Add a vector to each row of a matrix
mlblr = np.array([[1,2,3], [4,5,6]])
# mlblr has shape (2, 3) and eip has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(mlblr + eip)

# Add a vector to each column of a matrix
# mlblr has shape (2, 3) and eip_in has shape (2,).
# If we transpose mlblr then it has shape (3, 2) and can be broadcast
# against eip_in to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix mlblr with
# the vector eip_in added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((mlblr.T + eip_in).T)
# Another solution is to reshape eip_in to be a column vector of shape (2, 1);
# we can then broadcast it directly against mlblr to produce the same
# output.
print(mlblr + np.reshape(eip_in, (2, 1)))

# Multiply a matrix by a constant:
# mlblr has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(mlblr * 2)

Image operations

SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:

In [ ]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
eip = imread('assets/cat.jpg')
print(eip.dtype, eip.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
eip_in = eip * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
eip_in = imresize(eip_in, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', eip_in)

Distance between points

SciPy defines some useful functions for computing distances between sets of points.

The function scipy.spatial.distance.pdist computes the distance between all pairs of points in a given set:

In [ ]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
eip = np.array([[0, 1], [1, 0], [2, 0]])
print(eip)

# Compute the Euclidean distance between all rows of eip.
# mlblr[i, j] is the Euclidean distance between eip[i, :] and eip[j, :],
# and mlblr is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
mlblr = squareform(pdist(eip, 'euclidean'))
print(mlblr)

Plotting

The most important function in matplotlib is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the eip and mlblr coordinates for points on a sine curve
eip = np.arange(0, 3 * np.pi, 0.1)
mlblr = np.sin(eip)

# Plot the points using matplotlib
plt.plot(eip, mlblr)
plt.show()  # You must call plt.show() to make graphics appear.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the eip and y coordinates for points on sine and cosine curves
eip = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(eip)
y_cos = np.cos(eip)

# Plot the points using matplotlib
plt.plot(eip, y_sin)
plt.plot(eip, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

Subplots

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
eip = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(eip)
y_cos = np.cos(eip)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(eip, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(eip, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

Images

You can use the imshow function to show images. Here is an example:

In [ ]:
import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

img = imread('assets/cat.jpg')
img_tinted = img * [1, 0.95, 0.9]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(img_tinted))
plt.show()